// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiseRecipeExtractor.Infrastructure;

#nullable disable

namespace MiseRecipeExtractor.Infrastructure.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260806163018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeVersionId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "MiseRecipeExtractor.Core.Entities.Ingredient.Name#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Original")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Translated")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "MiseRecipeExtractor.Core.Entities.Ingredient.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double?>("Amount")
                                .HasColumnType("REAL");

                            b1.Property<int>("Confidence")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OriginalText")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Unit")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RecipeVersionId");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Source", "MiseRecipeExtractor.Core.Entities.Recipe.Source#SourceMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("ExtractedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OriginalLanguage")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceUrl")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.RecipeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Title", "MiseRecipeExtractor.Core.Entities.RecipeVersion.Title#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Original")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Translated")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeVersions", (string)null);
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OrderIsInferred")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RecipeVersionId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Text", "MiseRecipeExtractor.Core.Entities.Step.Text#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Original")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Translated")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RecipeVersionId");

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.Ingredient", b =>
                {
                    b.HasOne("MiseRecipeExtractor.Core.Entities.RecipeVersion", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.RecipeVersion", b =>
                {
                    b.HasOne("MiseRecipeExtractor.Core.Entities.Recipe", null)
                        .WithMany("Versions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.Step", b =>
                {
                    b.HasOne("MiseRecipeExtractor.Core.Entities.RecipeVersion", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.Recipe", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MiseRecipeExtractor.Core.Entities.RecipeVersion", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
